#!/usr/bin/env bash
# Fetches Firebase config keys and writes them to .env + GoogleService-Info.plist
# Prerequisites: run `npx -y firebase-tools@latest login` first

set -euo pipefail

PROJECT_ID="${1:-lawncare-72560}"
BUNDLE_ID="com.collins.lawncare"
WEB_APP_NICKNAME="Collins Lawncare Web"

echo "→ Checking Firebase login..."
if ! npx -y firebase-tools@latest login:list 2>/dev/null | grep -q "@"; then
  echo "Not logged in. Run: npx -y firebase-tools@latest login"
  exit 1
fi

echo "→ Using project: $PROJECT_ID"
if ! npx -y firebase-tools@latest projects:list 2>/dev/null | grep -q "$PROJECT_ID"; then
  echo "→ Creating Firebase project $PROJECT_ID..."
  npx -y firebase-tools@latest projects:create "$PROJECT_ID" --display-name "Collins Lawncare"
fi
npx -y firebase-tools@latest use "$PROJECT_ID"

echo "→ Finding or creating Web app..."
WEB_APP_ID=$(npx -y firebase-tools@latest apps:list WEB --project "$PROJECT_ID" 2>/dev/null \
  | awk '/│/ && !/App ID/ && !/┌/ && !/├/ && !/└/ { gsub(/ /,""); print $2; exit }' || true)
if [ -z "$WEB_APP_ID" ]; then
  WEB_APP_ID=$(npx -y firebase-tools@latest apps:create WEB "$WEB_APP_NICKNAME" --project "$PROJECT_ID" | awk '/App ID/ { print $NF }')
fi
echo "   Web App ID: $WEB_APP_ID"

echo "→ Finding or creating iOS app..."
IOS_APP_ID=$(npx -y firebase-tools@latest apps:list IOS --project "$PROJECT_ID" 2>/dev/null \
  | awk '/│/ && !/App ID/ && !/┌/ && !/├/ && !/└/ { gsub(/ /,""); print $2; exit }' || true)
if [ -z "$IOS_APP_ID" ]; then
  IOS_APP_ID=$(npx -y firebase-tools@latest apps:create IOS "$BUNDLE_ID" --project "$PROJECT_ID" --bundle-id "$BUNDLE_ID" | awk '/App ID/ { print $NF }')
fi
echo "   iOS App ID: $IOS_APP_ID"

echo "→ Fetching Web SDK config..."
WEB_CONFIG=$(npx -y firebase-tools@latest apps:sdkconfig WEB "$WEB_APP_ID" --project "$PROJECT_ID")

apiKey=$(echo "$WEB_CONFIG" | sed -n 's/.*apiKey: "\([^"]*\)".*/\1/p')
authDomain=$(echo "$WEB_CONFIG" | sed -n 's/.*authDomain: "\([^"]*\)".*/\1/p')
projectId=$(echo "$WEB_CONFIG" | sed -n 's/.*projectId: "\([^"]*\)".*/\1/p')
storageBucket=$(echo "$WEB_CONFIG" | sed -n 's/.*storageBucket: "\([^"]*\)".*/\1/p')
messagingSenderId=$(echo "$WEB_CONFIG" | sed -n 's/.*messagingSenderId: "\([^"]*\)".*/\1/p')
appId=$(echo "$WEB_CONFIG" | sed -n 's/.*appId: "\([^"]*\)".*/\1/p')
measurementId=$(echo "$WEB_CONFIG" | sed -n 's/.*measurementId: "\([^"]*\)".*/\1/p')

cat > .env <<EOF
# Generated by scripts/fetch-firebase-keys.sh — do not commit
VITE_FIREBASE_API_KEY=$apiKey
VITE_FIREBASE_AUTH_DOMAIN=$authDomain
VITE_FIREBASE_PROJECT_ID=$projectId
VITE_FIREBASE_STORAGE_BUCKET=$storageBucket
VITE_FIREBASE_MESSAGING_SENDER_ID=$messagingSenderId
VITE_FIREBASE_APP_ID=$appId
VITE_FIREBASE_MEASUREMENT_ID=$measurementId
EOF
echo "✓ Wrote .env"

echo "→ Fetching iOS GoogleService-Info.plist..."
mkdir -p ios/App/App
npx -y firebase-tools@latest apps:sdkconfig IOS "$IOS_APP_ID" --project "$PROJECT_ID" \
  | sed -n '/<?xml/,/<\/plist>/p' > ios/App/App/GoogleService-Info.plist
echo "✓ Wrote ios/App/App/GoogleService-Info.plist"

echo ""
echo "Done! Keys are in .env and GoogleService-Info.plist"
echo "Restart your dev server: npm run dev"
